import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        marginBottom: 20,
    },
    header: {marginBottom: 10},
    title: {fontSize: 20, fontWeight: '700', color: '#1F2937'},
    dateRange: {fontSize: 12, color: '#9CA3AF', fontWeight: '600', marginBottom: 6},
    weekSwitch: {
        flexDirection: 'row',
        backgroundColor: '#F3F4F6',
        borderRadius: 10,
        padding: 3,
        alignSelf: 'flex-start',
    },
    switchButton: {paddingVertical: 6, paddingHorizontal: 14, borderRadius: 8},
    switchButtonActive: {backgroundColor: '#5B8DEF'},
    switchText: {fontSize: 12, color: '#6B7280', fontWeight: '600'},
    switchTextActive: {color: '#FFFFFF'},
    filterButton: {
        paddingVertical: 6,
        paddingHorizontal: 14,
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        marginRight: 8,
    },
    filterButtonActive: {backgroundColor: '#5B8DEF'},
    filterText: {fontSize: 12, color: '#6B7280', fontWeight: '600'},
    filterTextActive: {color: '#FFFFFF'},
    chartWrapper: {marginVertical: 8, alignItems: 'center'},
    pointerLabel: {
        backgroundColor: '#1F2937',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 4,
    },
    pointerDay: {fontSize: 11, color: '#E5E7EB', fontWeight: '600'},
    pointerValue: {fontSize: 20, color: '#7C9FFF', fontWeight: '800'},
});