import { StyleSheet, Dimensions } from "react-native";
import { colors } from "@/src/shared/global/colors";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.black,
    },
    scannerContainer: {
        flex: 1,
        position: "relative",
    },
    overlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: "center",
        alignItems: "center",
    },
    overlayTop: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        width: "100%",
    },
    overlayMiddle: {
        flexDirection: "row",
        width: "100%",
    },
    overlaySide: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
    },
    scanArea: {
        width: width * 0.75,
        height: width * 0.75,
        position: "relative",
    },
    corner: {
        position: "absolute",
        width: 40,
        height: 40,
        borderColor: colors.white,
    },
    cornerTopLeft: {
        top: 0,
        left: 0,
        borderTopWidth: 4,
        borderLeftWidth: 4,
        borderTopLeftRadius: 8,
    },
    cornerTopRight: {
        top: 0,
        right: 0,
        borderTopWidth: 4,
        borderRightWidth: 4,
        borderTopRightRadius: 8,
    },
    cornerBottomLeft: {
        bottom: 0,
        left: 0,
        borderBottomWidth: 4,
        borderLeftWidth: 4,
        borderBottomLeftRadius: 8,
    },
    cornerBottomRight: {
        bottom: 0,
        right: 0,
        borderBottomWidth: 4,
        borderRightWidth: 4,
        borderBottomRightRadius: 8,
    },
    overlayBottom: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.6)",
        width: "100%",
    },
    instructionContainer: {
        position: "absolute",
        top: height * 0.45,
        left: 0,
        right: 0,
        alignItems: "center",
        paddingHorizontal: 40,
        paddingVertical: 8, // Added to accommodate button without large gaps
    },
    instructionBox: {
        backgroundColor: "rgba(255, 255, 255, 0.95)",
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 16,
        alignItems: "center",
    },
    instructionIcon: {
        marginBottom: 8,
    },
    instructionTitle: {
        fontSize: 24,
        fontWeight: "700",
        color: colors.black,
        marginBottom: 4,
    },
    instructionText: {
        fontSize: 16,
        color: "#6c757d",
        textAlign: "center",
    },
    manualEntryContainer: {
        position: "absolute",
        top: height * 0.356,
        left: 0,
        right: 8,
        alignItems: "center",
    },
    manualEntryButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: colors.white,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 25,
        borderColor: colors.primary,
        borderWidth: 2,
        gap: 8,
        marginBottom: 12, // Small gap between button and instructionBox
    },
    manualEntryText: {
        fontSize: 16,
        fontWeight: "600",
        color: colors.primary,
    },
    footer: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        paddingBottom: 50,
        paddingTop: 20,
        alignItems: "center",
        // backgroundColor: "rgba(0, 0, 0, 0.3)",
    },
    employeeButton: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: colors.white,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        gap: 8,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    employeeText: {
        fontSize: 15,
        fontWeight: "600",
        color: colors.primary,
    },
    modalBackground: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        justifyContent: "center",
        alignItems: "center",
    },
    modalBox: {
        width: "85%",
        backgroundColor: colors.white,
        padding: 28,
        borderRadius: 20,
        alignItems: "center",
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
        elevation: 8,
    },
    modalIcon: {
        marginBottom: 16,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "700",
        color: colors.black,
        marginBottom: 8,
        textAlign: "center",
    },
    modalText: {
        marginBottom: 24,
        fontSize: 15,
        color: "#6c757d",
        textAlign: "center",
        lineHeight: 22,
    },
    modalButton: {
        backgroundColor: colors.primary,
        paddingVertical: 14,
        paddingHorizontal: 32,
        borderRadius: 12,
        minWidth: 120,
    },
    cancelButton: {
        backgroundColor: "#6c757d",
    },
    modalButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    input: {
        width: "100%",
        borderWidth: 1,
        borderColor: "#e9ecef",
        borderRadius: 8,
        padding: 12,
        fontSize: 15,
        color: colors.black,
        marginBottom: 16,
    },
    modalButtonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        gap: 16,
    },
    notFoundModalButtonContainer: {
        flexDirection: "column",
        gap: 12,
    },
    reportButton: {
        marginTop: 8,
        backgroundColor: "#6c757d",
    },
});