import {StyleSheet} from "react-native";
import {colors} from "@/src/shared/global/colors";

export default StyleSheet.create({
    container: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
    },
    title: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1C1C1E',
        marginBottom: 16,
    },
    listContainer: {maxHeight: 400},
    productCard: {
        backgroundColor: '#F9F9F9',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    productHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    productInfo: {flex: 1, marginRight: 12},
    productName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1C1C1E',
        marginBottom: 2,
    },
    productNumber: {
        fontSize: 12,
        color: '#A0A0A0',
        marginBottom: 4,
    },
    badge: {paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8},
    badgeText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    stockInfo: {flexDirection: 'row', marginBottom: 12},
    stockItem: {flex: 1, alignItems: 'center'},
    stockDivider: {width: 1, backgroundColor: '#E5E5EA'},
    stockLabel: {fontSize: 11, color: '#8E8E93', marginBottom: 4},
    stockValue: {fontSize: 20, fontWeight: '700', color: '#1C1C1E'},
    progressBar: {
        height: 6,
        backgroundColor: '#E5E5EA',
        borderRadius: 3,
        overflow: 'hidden',
    },
    progressFill: {height: '100%', borderRadius: 3},
    loadingContainer: {
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyContainer: {
        height: 150,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    emptyText: {fontSize: 15, color: '#8E8E93', textAlign: 'center'},
    subtitle: {
        fontSize: 13,
        color: '#8E8E93',
        marginTop: 4,
    },
    loadMoreButton: {
        backgroundColor: '#F9F9F9',
        borderRadius: 12,
        padding: 16,
        marginTop: 4,
        marginBottom: 12,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E5E5EA',
        borderStyle: 'dashed',
    },
    loadMoreText: {
        fontSize: 15,
        fontWeight: '600',
        color: colors.black,
        marginBottom: 4,
    },
    loadMoreSubtext: {
        fontSize: 12,
        color: '#8E8E93',
    },
});